-- supabase-schema.sql
-- Run this script in your Supabase project's SQL Editor to set up the database structure.

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Plants table
create table public.plants (
    id text primary key,
    name text not null,
    location text not null,
    capacity integer not null,
    target_oee integer not null
);

-- Seed plants
insert into public.plants (id, name, location, capacity, target_oee) values
('plant-1', 'Detroit Engine Plant', 'Detroit, MI', 5000, 85),
('plant-2', 'Munich Assembly', 'Munich, Germany', 3200, 90),
('plant-3', 'Tokyo Assembly', 'Tokyo, Japan', 4500, 88)
on conflict (id) do update set
    name = excluded.name,
    location = excluded.location,
    capacity = excluded.capacity,
    target_oee = excluded.target_oee;

-- 2. User Profiles table (maps auth.users to roles and plants)
create table public.profiles (
    id uuid references auth.users on delete cascade primary key,
    email text unique not null,
    name text not null,
    role text not null check (role in ('Super Admin', 'Plant Admin', 'User', 'Admin', 'Viewer')),
    plant_id text not null, -- 'all' for Super Admin, or a specific plant_id
    active boolean not null default true
);

-- 3. Production Data table
create table public.production_data (
    id text primary key, -- composite: plant_id + timestamp
    plant_id text references public.plants(id) on delete cascade,
    timestamp timestamp with time zone not null,
    date text not null,
    hour integer not null,
    shift text not null,
    target_parts integer not null,
    actual_parts integer not null,
    reject_parts integer not null,
    uptime_minutes integer not null,
    downtime_reason text
);

-- Add index on plant_id and date for fast dashboard/trends queries
create index idx_prod_plant_date on public.production_data(plant_id, date);
create index idx_prod_timestamp on public.production_data(timestamp);

-- 4. Report History table
create table public.report_history (
    id text primary key,
    name text not null,
    type text not null,
    date_range text not null,
    shift text not null,
    plant_id text not null,
    generated_at timestamp with time zone default now(),
    created_by text
);

-- 5. Scheduled Reports table
create table public.scheduled_reports (
    id text primary key,
    plant_id text not null,
    report_type text not null,
    frequency text not null,
    time text not null,
    email_recipients text not null,
    enabled boolean not null default true,
    last_run timestamp with time zone,
    format_pdf boolean not null default true,
    format_excel boolean not null default true
);

-- Seed default schedules
insert into public.scheduled_reports (id, plant_id, report_type, frequency, time, email_recipients, enabled, format_pdf, format_excel) values
('sched-1', 'plant-1', 'Daily Report', 'Daily', '07:00', 'plantadmin@plant.com, exec-alerts@plant.com', true, true, true),
('sched-2', 'plant-1', 'Shift Report', 'Daily', '14:15', 'shift-a-team@plant.com', true, true, true),
('sched-3', 'plant-2', 'Weekly Report', 'Weekly', '08:00', 'munichadmin@plant.com', false, true, true)
on conflict (id) do nothing;

-- 6. Email Configuration table
create table public.email_configuration (
    id text primary key default 'default',
    host text not null,
    port integer not null,
    username text not null,
    password text not null,
    secure boolean not null default true,
    logo_text text not null,
    header_color text not null,
    footer_text text not null
);

-- Seed default configs
insert into public.email_configuration (id, host, port, username, password, secure, logo_text, header_color, footer_text) values
('default', 'smtp.industrialcloud.com', 587, 'alerts@industrialcloud.com', '••••••••••••', true, 'INDUSTRIAL SKADOMATION SOLUTIONS', '#0F172A', 'This is an automated production report. Confidential. Generated by Cloud Sync.')
on conflict (id) do nothing;

-- 7. Synchronization Logs table
create table public.synchronization_logs (
    id uuid primary key default uuid_generate_v4(),
    timestamp timestamp with time zone default now(),
    status_type text not null, -- 'SUCCESS', 'FAILED', 'INFO'
    log_message text not null
);

-- Setup Row Level Security (RLS)
alter table public.plants enable row level security;
alter table public.profiles enable row level security;
alter table public.production_data enable row level security;
alter table public.report_history enable row level security;
alter table public.scheduled_reports enable row level security;
alter table public.email_configuration enable row level security;
alter table public.synchronization_logs enable row level security;

-- Setup Public Read Access / Authenticated Edit Access policies for demo simplicity
create policy "Allow all users full access to plants" on public.plants for all using (true) with check (true);
create policy "Allow all users full access to profiles" on public.profiles for all using (true) with check (true);
create policy "Allow all users full access to production_data" on public.production_data for all using (true) with check (true);
create policy "Allow all users full access to report_history" on public.report_history for all using (true) with check (true);
create policy "Allow all users full access to scheduled_reports" on public.scheduled_reports for all using (true) with check (true);
create policy "Allow all users full access to email_configuration" on public.email_configuration for all using (true) with check (true);
create policy "Allow all users full access to synchronization_logs" on public.synchronization_logs for all using (true) with check (true);

-- Enable Realtime for live updates (optional but helpful for dashboard)
alter publication supabase_realtime add table public.production_data;
alter publication supabase_realtime add table public.synchronization_logs;

-- Helper functions for database schema dynamic discovery
CREATE OR REPLACE FUNCTION public.count_rows(schema_name text, table_name text)
RETURNS bigint SECURITY DEFINER AS $$
DECLARE
    result bigint;
    query text;
BEGIN
    query := 'SELECT count(*) FROM ' || quote_ident(schema_name) || '.' || quote_ident(table_name);
    EXECUTE query INTO result;
    RETURN result;
EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.discover_database_structure()
RETURNS json SECURITY DEFINER AS $$
DECLARE
    result json;
BEGIN
    SELECT json_build_object(
        'tables', COALESCE(
            (
                SELECT json_agg(
                    json_build_object(
                        'name', t.table_name::text,
                        'schema', t.table_schema::text,
                        'recordCount', public.count_rows(t.table_schema, t.table_name),
                        'primaryKey', COALESCE(
                            (
                                SELECT kcu.column_name::text
                                FROM information_schema.table_constraints tc
                                JOIN information_schema.key_column_usage kcu 
                                  ON tc.constraint_name = kcu.constraint_name
                                  AND tc.table_schema = kcu.table_schema
                                WHERE tc.constraint_type = 'PRIMARY KEY'
                                  AND tc.table_schema = t.table_schema
                                  AND tc.table_name = t.table_name
                                LIMIT 1
                            ), 'id'
                        ),
                        'status', 'ACTIVE',
                        'columns', COALESCE(
                            (
                                SELECT json_agg(
                                    json_build_object(
                                        'name', c.column_name::text,
                                        'type', c.data_type::text,
                                        'isPk', COALESCE(
                                            (
                                                SELECT true
                                                FROM information_schema.table_constraints tc
                                                JOIN information_schema.key_column_usage kcu 
                                                  ON tc.constraint_name = kcu.constraint_name
                                                  AND tc.table_schema = kcu.table_schema
                                                WHERE tc.constraint_type = 'PRIMARY KEY'
                                                  AND tc.table_schema = c.table_schema
                                                  AND tc.table_name = c.table_name
                                                  AND kcu.column_name = c.column_name
                                                LIMIT 1
                                            ), false
                                        )
                                    )
                                )
                                FROM information_schema.columns c
                                WHERE c.table_schema = t.table_schema
                                  AND c.table_name = t.table_name
                            ), '[]'::json
                        )
                    )
                )
                FROM information_schema.tables t
                WHERE t.table_schema = 'public'
                  AND t.table_type = 'BASE TABLE'
            ), '[]'::json
        )
    ) INTO result;
    
    RETURN result;
END;
$$ LANGUAGE plpgsql;

GRANT EXECUTE ON FUNCTION public.count_rows(text, text) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.discover_database_structure() TO anon, authenticated;

-- 10. Automatically Create User Profile on Auth SignUp / Admin User Creation
CREATE OR REPLACE FUNCTION public.handle_new_user_admin()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    INSERT INTO public.profiles (id, email, name, role, plant_id, active)
    VALUES (
        new.id,
        new.email,
        COALESCE(new.raw_user_meta_data->>'name', ''),
        COALESCE(new.raw_user_meta_data->>'role', 'User'),
        COALESCE(new.raw_user_meta_data->>'plant_id', 'plant-1'),
        COALESCE((new.raw_user_meta_data->>'active')::boolean, true)
    );
    RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created_admin ON auth.users;

CREATE TRIGGER on_auth_user_created_admin
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user_admin();

